### ISSUE TITLE
Question: How does it work in case domain name changes?

### ISSUE THREAD

**Issue by hassanfarid** [stepchowfun/hashpass#11]
Hi,
My question is how does it work if the service domain name changes from `www.facebook.com` to `login.facebook.com` ?

In case it is using the domain name of the password box as-is, it may fail to produce the same password.

**Comment by stepchowfun** [comment]
Hi @hassanfarid, Hashpass is completely stateless, so the behavior is as you described: if a website changes its domain name, then you will have to manually enter the old domain name to produce your password (until you update your password accordingly). This happens occasionally, and it can be annoying, but it's the price to pay for using a completely stateless password manager.

(Note that the domain is an editable text field, so you can change it as needed.)
