### ISSUE TITLE
Link compatible client

### ISSUE THREAD

**Issue by binaryplease** [stepchowfun/hashpass#8]
Hi, 

first of all, great project, I really like your idea!
So much in fact, that I implemented a compatible client for the command line over here: https://github.com/binaryplease/go-hashpass

I hope that is okay, I don't want to steal any of work and ideas. You link a compatible python script at the bottom of your repo, I wrote my app in Go because it allows me to run the binary on any system without having to install python.

Just wanted to leave a comment in case you want to link to the project in the README.
Cheers!

**Comment by stepchowfun** [comment]
Hey that's great! I'll add a link. :)

**Comment by stepchowfun** [comment]
Fixed by https://github.com/stepchowfun/hashpass/pull/9.
